-- Gymind Supabase QA seed
-- Paste this whole file into Supabase SQL Editor and run it against a dev/test database only.
-- Password for every qa.*@gymind.test account: Test@123456
-- BCrypt hash generated for Test@123456:
-- $2a$11$8WPV3sOk1fOQ3Vx0/7SFBOMG0ZjUnEOuMK64BSRTn.D.Y/eOvqigq

begin;

create table if not exists public.membership_plan_branches (
  id bigint generated by default as identity primary key,
  membership_plan_id bigint not null references public.membership_plans(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  constraint uq_membership_plan_branches_plan_branch unique (membership_plan_id, branch_id)
);

insert into public.roles (name)
select role_name
from (values
  ('SuperAdmin'),
  ('GymOwner'),
  ('BranchManager'),
  ('Staff'),
  ('Trainer'),
  ('Member')
) as seed(role_name)
where not exists (
  select 1 from public.roles r where r.name = seed.role_name
);

do $$
declare
  qa_password_hash constant text := '$2a$11$8WPV3sOk1fOQ3Vx0/7SFBOMG0ZjUnEOuMK64BSRTn.D.Y/eOvqigq';
  gym1_id bigint;
  gym2_id bigint;
  gym3_id bigint;
  main_id bigint;
  east_id bigint;
  beirut_id bigint;
  strength_id bigint;
  cardio_id bigint;
  solo_id bigint;
  owner1_id bigint;
  owner2_id bigint;
  owner3_id bigint;
  staff_id bigint;
  trainer_elie_id bigint;
  trainer_marc_id bigint;
  trainer_rana_id bigint;
  day_pass_id bigint;
  monthly_id bigint;
  three_month_id bigint;
  vip_id bigint;
  freeze_id bigint;
  gym2_monthly_id bigint;
  gym3_monthly_id bigint;
  active_member_id bigint;
  daypass_member_id bigint;
  three_member_id bigint;
  vip_member_id bigint;
  expiring2_member_id bigint;
  expiring_tomorrow_member_id bigint;
  expired_member_id bigint;
  frozen_member_id bigint;
  cancelled_member_id bigint;
  noplan_member_id bigint;
  history_member_id bigint;
  running_member_id bigint;
  vip_beirut_member_id bigint;
  gym2_member_id bigint;
  gym3_member_id bigint;
  strength_class_id bigint;
  hiit_class_id bigint;
  spinning_class_id bigint;
  notification_id bigint;
begin
  insert into public.gyms (name, city, is_active, created_at)
  select 'Gymind Ablah Fitness', 'Ablah', true, now()
  where not exists (select 1 from public.gyms where name = 'Gymind Ablah Fitness');

  insert into public.gyms (name, city, is_active, created_at)
  select 'Gymind Local Gym', 'Ablah', true, now()
  where not exists (select 1 from public.gyms where name = 'Gymind Local Gym');

  insert into public.gyms (name, city, is_active, created_at)
  select 'Gymind Solo Gym', 'Ablah', true, now()
  where not exists (select 1 from public.gyms where name = 'Gymind Solo Gym');

  select id into gym1_id from public.gyms where name = 'Gymind Ablah Fitness';
  select id into gym2_id from public.gyms where name = 'Gymind Local Gym';
  select id into gym3_id from public.gyms where name = 'Gymind Solo Gym';

  insert into public.branches (gym_id, name, address, phone, range_km, capacity, area_sqm, lat, lng, open_time, close_time, qr_code_token, qr_code_created_at, qr_code_updated_at, qr_code_is_active, is_active)
  select gym1_id, 'Ablah Main Branch', 'Ablah, Bekaa, Lebanon', '70111001', 0.15, 120, 480, 33.8212, 35.9956, '06:00', '23:00', md5('QA_ABLAH_MAIN'), now(), now(), true, true
  where not exists (select 1 from public.branches where name = 'Ablah Main Branch');

  insert into public.branches (gym_id, name, address, phone, range_km, capacity, area_sqm, lat, lng, open_time, close_time, qr_code_token, qr_code_created_at, qr_code_updated_at, qr_code_is_active, is_active)
  select gym1_id, 'Ablah East Branch', 'Ablah, Bekaa, Lebanon', '70111002', 0.15, 90, 360, 33.8224, 35.9991, '06:00', '23:00', md5('QA_ABLAH_EAST'), now(), now(), true, true
  where not exists (select 1 from public.branches where name = 'Ablah East Branch');

  insert into public.branches (gym_id, name, address, phone, range_km, capacity, area_sqm, lat, lng, open_time, close_time, qr_code_token, qr_code_created_at, qr_code_updated_at, qr_code_is_active, is_active)
  select gym1_id, 'Beirut Branch', 'Beirut, Lebanon', '70111003', 0.15, 150, 600, 33.8938, 35.5018, '06:00', '23:00', md5('QA_BEIRUT'), now(), now(), true, true
  where not exists (select 1 from public.branches where name = 'Beirut Branch');

  insert into public.branches (gym_id, name, address, phone, range_km, capacity, area_sqm, lat, lng, open_time, close_time, qr_code_token, qr_code_created_at, qr_code_updated_at, qr_code_is_active, is_active)
  select gym2_id, 'Ablah Strength Branch', 'Ablah, Bekaa, Lebanon', '70222001', 0.15, 80, 320, 33.8206, 35.9944, '06:00', '23:00', md5('QA_ABLAH_STRENGTH'), now(), now(), true, true
  where not exists (select 1 from public.branches where name = 'Ablah Strength Branch');

  insert into public.branches (gym_id, name, address, phone, range_km, capacity, area_sqm, lat, lng, open_time, close_time, qr_code_token, qr_code_created_at, qr_code_updated_at, qr_code_is_active, is_active)
  select gym2_id, 'Ablah Cardio Branch', 'Ablah, Bekaa, Lebanon', '70222002', 0.15, 70, 280, 33.8231, 35.9962, '06:00', '23:00', md5('QA_ABLAH_CARDIO'), now(), now(), true, true
  where not exists (select 1 from public.branches where name = 'Ablah Cardio Branch');

  insert into public.branches (gym_id, name, address, phone, range_km, capacity, area_sqm, lat, lng, open_time, close_time, qr_code_token, qr_code_created_at, qr_code_updated_at, qr_code_is_active, is_active)
  select gym3_id, 'Ablah Solo Branch', 'Ablah, Bekaa, Lebanon', '70333001', 0.15, 60, 240, 33.8217, 35.9936, '06:00', '23:00', md5('QA_ABLAH_SOLO'), now(), now(), true, true
  where not exists (select 1 from public.branches where name = 'Ablah Solo Branch');

  select id into main_id from public.branches where name = 'Ablah Main Branch';
  select id into east_id from public.branches where name = 'Ablah East Branch';
  select id into beirut_id from public.branches where name = 'Beirut Branch';
  select id into strength_id from public.branches where name = 'Ablah Strength Branch';
  select id into cardio_id from public.branches where name = 'Ablah Cardio Branch';
  select id into solo_id from public.branches where name = 'Ablah Solo Branch';

  create temp table if not exists qa_user_seed (
    email text primary key,
    full_name text not null,
    phone text,
    role_name text not null,
    gym_id bigint,
    branch_id bigint
  ) on commit drop;

  truncate table qa_user_seed;

  insert into qa_user_seed (email, full_name, phone, role_name, gym_id, branch_id) values
    ('qa.superadmin@gymind.test', 'QA Super Admin', '71900001', 'SuperAdmin', null, null),
    ('qa.owner.ablahfitness@gymind.test', 'QA Ablah Fitness Owner', '71900002', 'GymOwner', gym1_id, main_id),
    ('qa.owner.localgym@gymind.test', 'QA Local Gym Owner', '71900003', 'GymOwner', gym2_id, strength_id),
    ('qa.owner.sologym@gymind.test', 'QA Solo Gym Owner', '71900004', 'GymOwner', gym3_id, solo_id),
    ('qa.manager.ablahmain@gymind.test', 'QA Ablah Main Manager', '71900005', 'BranchManager', gym1_id, main_id),
    ('qa.staff.ablahmain@gymind.test', 'QA Ablah Main Staff', '71900006', 'Staff', gym1_id, main_id),
    ('qa.trainer.elie@gymind.test', 'Elie Haddad', '71900007', 'Trainer', gym1_id, main_id),
    ('qa.trainer.marc@gymind.test', 'Marc Khoury', '71900008', 'Trainer', gym1_id, east_id),
    ('qa.trainer.rana@gymind.test', 'Rana Nader', '71900009', 'Trainer', gym1_id, beirut_id),
    ('qa.member.active.monthly@gymind.test', 'Charbel Active Monthly', '71810001', 'Member', gym1_id, main_id),
    ('qa.member.daypass@gymind.test', 'Maya Daypass', '71810002', 'Member', gym1_id, main_id),
    ('qa.member.3months@gymind.test', 'Jad ThreeMonths', '71810003', 'Member', gym1_id, east_id),
    ('qa.member.vip@gymind.test', 'Lea VIP', '71810004', 'Member', gym1_id, main_id),
    ('qa.member.expiring2days@gymind.test', 'Karim Expiring Soon', '71810005', 'Member', gym1_id, main_id),
    ('qa.member.expiringtomorrow@gymind.test', 'Nour Expiring Tomorrow', '71810006', 'Member', gym1_id, main_id),
    ('qa.member.expired@gymind.test', 'Tony Expired', '71810007', 'Member', gym1_id, main_id),
    ('qa.member.frozen@gymind.test', 'Sarah Frozen', '71810008', 'Member', gym1_id, east_id),
    ('qa.member.cancelled@gymind.test', 'Rami Cancelled', '71810009', 'Member', gym1_id, main_id),
    ('qa.member.noplan@gymind.test', 'Hiba NoPlan', '71810010', 'Member', gym1_id, main_id),
    ('qa.member.history@gymind.test', 'Paul History', '71810011', 'Member', gym1_id, main_id),
    ('qa.member.running@gymind.test', 'Rita Running Timer', '71810012', 'Member', gym1_id, main_id),
    ('qa.member.vip.beirut@gymind.test', 'George VIP Beirut', '71810013', 'Member', gym1_id, beirut_id),
    ('qa.member.gym2.monthly@gymind.test', 'Maria GymTwo', '71810014', 'Member', gym2_id, strength_id),
    ('qa.member.gym3.solo@gymind.test', 'Sami Solo', '71810015', 'Member', gym3_id, solo_id);

  insert into public.users (gym_id, branch_id, role_id, full_name, email, phone, password_hash, is_active, created_at)
  select s.gym_id, s.branch_id, r.id, s.full_name, s.email, s.phone, qa_password_hash, true, now()
  from qa_user_seed s
  join public.roles r on r.name = s.role_name
  where not exists (select 1 from public.users u where u.email = s.email);

  -- Explicit member-user repair for databases where only admin/staff QA users
  -- were inserted during an earlier failed/partial run.
  insert into public.users (gym_id, branch_id, role_id, full_name, email, phone, password_hash, is_active, created_at)
  select s.gym_id, s.branch_id, r.id, s.full_name, s.email, s.phone, qa_password_hash, true, now()
  from qa_user_seed s
  join lateral (
    select id
    from public.roles
    where lower(name) = 'member'
    order by id
    limit 1
  ) r on true
  where s.email like 'qa.member.%@gymind.test'
    and not exists (select 1 from public.users u where u.email = s.email);

  update public.users u
  set gym_id = s.gym_id,
      branch_id = s.branch_id,
      role_id = r.id,
      full_name = s.full_name,
      phone = s.phone,
      password_hash = qa_password_hash,
      is_active = true
  from qa_user_seed s
  join public.roles r on r.name = s.role_name
  where u.email = s.email;

  update public.users u
  set role_id = r.id,
      gym_id = s.gym_id,
      branch_id = s.branch_id,
      full_name = s.full_name,
      phone = s.phone,
      password_hash = qa_password_hash,
      is_active = true
  from qa_user_seed s
  join lateral (
    select id
    from public.roles
    where lower(name) = 'member'
    order by id
    limit 1
  ) r on true
  where u.email = s.email
    and s.email like 'qa.member.%@gymind.test';

  select id into owner1_id from public.users where email = 'qa.owner.ablahfitness@gymind.test';
  select id into owner2_id from public.users where email = 'qa.owner.localgym@gymind.test';
  select id into owner3_id from public.users where email = 'qa.owner.sologym@gymind.test';
  select id into staff_id from public.users where email = 'qa.staff.ablahmain@gymind.test';
  select id into trainer_elie_id from public.users where email = 'qa.trainer.elie@gymind.test';
  select id into trainer_marc_id from public.users where email = 'qa.trainer.marc@gymind.test';
  select id into trainer_rana_id from public.users where email = 'qa.trainer.rana@gymind.test';

  update public.gyms set owner_user_id = owner1_id where id = gym1_id;
  update public.gyms set owner_user_id = owner2_id where id = gym2_id;
  update public.gyms set owner_user_id = owner3_id where id = gym3_id;

  insert into public.members (gym_id, home_branch_id, user_id, full_name, phone, email, qr_code, join_date, is_active)
  select s.gym_id, s.branch_id, u.id, s.full_name, s.phone, s.email, 'QA-' || u.id::text, current_date - 45, true
  from qa_user_seed s
  join public.users u on u.email = s.email
  where s.role_name = 'Member'
    and not exists (select 1 from public.members m where m.email = s.email);

  update public.members m
  set gym_id = s.gym_id,
      home_branch_id = s.branch_id,
      user_id = u.id,
      full_name = s.full_name,
      phone = s.phone,
      is_active = true
  from qa_user_seed s
  join public.users u on u.email = s.email
  where m.email = s.email
    and s.role_name = 'Member';

  -- Defensive repair: if a previous run inserted QA member users but failed before
  -- public.members, create the missing member profiles from the stable email map.
  insert into public.members (gym_id, home_branch_id, user_id, full_name, phone, email, qr_code, join_date, is_active)
  select
    s.gym_id,
    s.branch_id,
    u.id,
    s.full_name,
    s.phone,
    s.email,
    'QA-' || u.id::text,
    current_date - 45,
    true
  from qa_user_seed s
  join public.users u on u.email = s.email
  left join public.members m on m.user_id = u.id
  where s.role_name = 'Member'
    and m.id is null;

  insert into public.member_profiles (member_id, height_cm, weight_kg, fitness_goal, created_at, updated_at)
  select m.id, 175, 76, 'QA demo member profile', now(), now()
  from public.members m
  join public.users u on u.id = m.user_id
  where u.email like 'qa.member.%@gymind.test'
    and not exists (select 1 from public.member_profiles mp where mp.member_id = m.id);

  insert into public.membership_plans (gym_id, name, price, duration_month, access_type, includes_classes, includes_pt, is_active)
  select gym_id, plan_name, price, duration_month, access_type, includes_classes, includes_pt, true
  from (values
    (gym1_id, 'QA One Day Pass', 5::numeric, 1, 'DAY_PASS', true, false),
    (gym1_id, 'QA Monthly Basic', 30::numeric, 1, 'one_branch', true, false),
    (gym1_id, 'QA 3-Month Standard', 80::numeric, 3, 'one_branch', true, false),
    (gym1_id, 'QA VIP All Branches', 120::numeric, 1, 'multi-branch', true, true),
    (gym1_id, 'QA Student Plan', 20::numeric, 1, 'one_branch', true, false),
    (gym1_id, 'QA Freeze Allowed Plan', 40::numeric, 1, 'one_branch', true, false),
    (gym2_id, 'QA Gym2 One Day Pass', 5::numeric, 1, 'DAY_PASS', true, false),
    (gym2_id, 'QA Monthly Local', 28::numeric, 1, 'one_branch', true, false),
    (gym2_id, 'QA VIP Local All Branches', 85::numeric, 1, 'multi-branch', true, false),
    (gym3_id, 'QA Solo One Day Pass', 5::numeric, 1, 'DAY_PASS', true, false),
    (gym3_id, 'QA Monthly Solo', 25::numeric, 1, 'one_branch', true, false)
  ) as p(gym_id, plan_name, price, duration_month, access_type, includes_classes, includes_pt)
  where not exists (
    select 1 from public.membership_plans mp
    where mp.gym_id = p.gym_id and mp.name = p.plan_name
  );

  select id into day_pass_id from public.membership_plans where gym_id = gym1_id and name = 'QA One Day Pass';
  select id into monthly_id from public.membership_plans where gym_id = gym1_id and name = 'QA Monthly Basic';
  select id into three_month_id from public.membership_plans where gym_id = gym1_id and name = 'QA 3-Month Standard';
  select id into vip_id from public.membership_plans where gym_id = gym1_id and name = 'QA VIP All Branches';
  select id into freeze_id from public.membership_plans where gym_id = gym1_id and name = 'QA Freeze Allowed Plan';
  select id into gym2_monthly_id from public.membership_plans where gym_id = gym2_id and name = 'QA Monthly Local';
  select id into gym3_monthly_id from public.membership_plans where gym_id = gym3_id and name = 'QA Monthly Solo';

  insert into public.membership_plan_branches (membership_plan_id, branch_id, created_at)
  select plan_id, branch_id, now()
  from (values
    (day_pass_id, main_id),
    (monthly_id, main_id),
    (three_month_id, east_id),
    (vip_id, main_id),
    (vip_id, east_id),
    (vip_id, beirut_id),
    ((select id from public.membership_plans where gym_id = gym1_id and name = 'QA Student Plan'), main_id),
    (freeze_id, east_id),
    ((select id from public.membership_plans where gym_id = gym2_id and name = 'QA Gym2 One Day Pass'), strength_id),
    (gym2_monthly_id, strength_id),
    ((select id from public.membership_plans where gym_id = gym2_id and name = 'QA VIP Local All Branches'), strength_id),
    ((select id from public.membership_plans where gym_id = gym2_id and name = 'QA VIP Local All Branches'), cardio_id),
    ((select id from public.membership_plans where gym_id = gym3_id and name = 'QA Solo One Day Pass'), solo_id),
    (gym3_monthly_id, solo_id)
  ) as pb(plan_id, branch_id)
  where plan_id is not null
    and branch_id is not null
    and not exists (
      select 1 from public.membership_plan_branches existing
      where existing.membership_plan_id = pb.plan_id and existing.branch_id = pb.branch_id
    );

  select m.id into active_member_id from public.members m where m.email = 'qa.member.active.monthly@gymind.test';
  select m.id into daypass_member_id from public.members m where m.email = 'qa.member.daypass@gymind.test';
  select m.id into three_member_id from public.members m where m.email = 'qa.member.3months@gymind.test';
  select m.id into vip_member_id from public.members m where m.email = 'qa.member.vip@gymind.test';
  select m.id into expiring2_member_id from public.members m where m.email = 'qa.member.expiring2days@gymind.test';
  select m.id into expiring_tomorrow_member_id from public.members m where m.email = 'qa.member.expiringtomorrow@gymind.test';
  select m.id into expired_member_id from public.members m where m.email = 'qa.member.expired@gymind.test';
  select m.id into frozen_member_id from public.members m where m.email = 'qa.member.frozen@gymind.test';
  select m.id into cancelled_member_id from public.members m where m.email = 'qa.member.cancelled@gymind.test';
  select m.id into noplan_member_id from public.members m where m.email = 'qa.member.noplan@gymind.test';
  select m.id into history_member_id from public.members m where m.email = 'qa.member.history@gymind.test';
  select m.id into running_member_id from public.members m where m.email = 'qa.member.running@gymind.test';
  select m.id into vip_beirut_member_id from public.members m where m.email = 'qa.member.vip.beirut@gymind.test';
  select m.id into gym2_member_id from public.members m where m.email = 'qa.member.gym2.monthly@gymind.test';
  select m.id into gym3_member_id from public.members m where m.email = 'qa.member.gym3.solo@gymind.test';

  insert into public.member_memberships (member_id, plan_id, start_date, end_date, status, freeze_days)
  select member_id, plan_id, start_date, end_date, status, freeze_days
  from (values
    (active_member_id, monthly_id, current_date - 5, current_date + 25, 'ACTIVE', 0),
    (daypass_member_id, day_pass_id, current_date, current_date, 'ACTIVE', 0),
    (three_member_id, three_month_id, current_date - 20, current_date + 70, 'ACTIVE', 0),
    (vip_member_id, vip_id, current_date - 3, current_date + 27, 'ACTIVE', 0),
    (expiring2_member_id, monthly_id, current_date - 28, current_date + 2, 'ACTIVE', 0),
    (expiring_tomorrow_member_id, monthly_id, current_date - 29, current_date + 1, 'ACTIVE', 0),
    (expired_member_id, monthly_id, current_date - 40, current_date - 10, 'EXPIRED', 0),
    (frozen_member_id, freeze_id, current_date - 10, current_date + 20, 'FROZEN', 7),
    (cancelled_member_id, monthly_id, current_date - 10, current_date + 20, 'CANCELLED', 0),
    (running_member_id, monthly_id, current_date - 7, current_date + 23, 'ACTIVE', 0),
    (vip_beirut_member_id, vip_id, current_date - 4, current_date + 26, 'ACTIVE', 0),
    (gym2_member_id, gym2_monthly_id, current_date - 4, current_date + 26, 'ACTIVE', 0),
    (gym3_member_id, gym3_monthly_id, current_date - 4, current_date + 26, 'ACTIVE', 0)
  ) as mm(member_id, plan_id, start_date, end_date, status, freeze_days)
  where member_id is not null
    and plan_id is not null
    and not exists (
      select 1 from public.member_memberships existing
      where existing.member_id = mm.member_id
        and existing.plan_id = mm.plan_id
        and existing.status = mm.status
    );

  insert into public.member_memberships (member_id, plan_id, start_date, end_date, status, freeze_days)
  select history_member_id, day_pass_id, current_date - 90, current_date - 90, 'EXPIRED', 0
  where not exists (select 1 from public.member_memberships where member_id = history_member_id and plan_id = day_pass_id);

  insert into public.member_memberships (member_id, plan_id, start_date, end_date, status, freeze_days)
  select history_member_id, monthly_id, current_date - 60, current_date - 30, 'EXPIRED', 0
  where not exists (select 1 from public.member_memberships where member_id = history_member_id and plan_id = monthly_id);

  insert into public.member_memberships (member_id, plan_id, start_date, end_date, status, freeze_days)
  select history_member_id, three_month_id, current_date - 5, current_date + 85, 'ACTIVE', 0
  where not exists (select 1 from public.member_memberships where member_id = history_member_id and plan_id = three_month_id and status = 'ACTIVE');

  insert into public.check_ins (member_id, branch_id, check_in_time, check_out_time, last_seen_at, status, method, check_out_method)
  select active_member_id, main_id, now() - interval '1 day 2 hours', now() - interval '1 day 1 hour', now() - interval '1 day 1 hour', 'CHECKED_OUT', 'QA_COMPLETED', 'QA_SEED'
  where not exists (select 1 from public.check_ins where member_id = active_member_id and method = 'QA_COMPLETED');

  insert into public.check_ins (member_id, branch_id, check_in_time, check_out_time, last_seen_at, status, method, check_out_method)
  select vip_member_id, east_id, date_trunc('day', now()) - interval '30 minutes', date_trunc('day', now()) + interval '30 minutes', date_trunc('day', now()) + interval '30 minutes', 'CHECKED_OUT', 'QA_CROSS_MIDNIGHT', 'QA_SEED'
  where not exists (select 1 from public.check_ins where member_id = vip_member_id and method = 'QA_CROSS_MIDNIGHT');

  insert into public.check_ins (member_id, branch_id, check_in_time, check_out_time, last_seen_at, status, method)
  select running_member_id, main_id, now() - interval '35 minutes', null, now() - interval '2 minutes', 'CHECKED_IN', 'QA_ACTIVE'
  where not exists (select 1 from public.check_ins where member_id = running_member_id and check_out_time is null);

  insert into public.check_ins (member_id, branch_id, check_in_time, check_out_time, last_seen_at, status, method)
  select vip_beirut_member_id, beirut_id, now() - interval '35 minutes', null, now() - interval '2 minutes', 'CHECKED_IN', 'QA_ACTIVE_VIP_BRANCH'
  where not exists (select 1 from public.check_ins where member_id = vip_beirut_member_id and check_out_time is null);

  insert into public.classes (gym_id, branch_id, trainer_user_id, name, capacity, start_time, end_time)
  select gym_id, branch_id, trainer_user_id, class_name, capacity, start_time, end_time
  from (values
    (gym1_id, main_id, trainer_elie_id, 'QA Strength Training Today', 20, date_trunc('day', now()) + interval '18 hours', date_trunc('day', now()) + interval '19 hours'),
    (gym1_id, main_id, trainer_elie_id, 'QA Strength Training Tomorrow', 20, date_trunc('day', now()) + interval '1 day 18 hours', date_trunc('day', now()) + interval '1 day 19 hours'),
    (gym1_id, main_id, trainer_elie_id, 'QA HIIT Tomorrow', 15, date_trunc('day', now()) + interval '1 day 17 hours', date_trunc('day', now()) + interval '1 day 18 hours'),
    (gym1_id, main_id, trainer_marc_id, 'QA Boxing Full Scenario', 1, date_trunc('day', now()) + interval '3 days 19 hours', date_trunc('day', now()) + interval '3 days 20 hours'),
    (gym1_id, east_id, trainer_marc_id, 'QA Yoga Available', 12, date_trunc('day', now()) + interval '2 days 8 hours', date_trunc('day', now()) + interval '2 days 9 hours'),
    (gym1_id, east_id, trainer_marc_id, 'QA Bodybuilding Basics', 18, date_trunc('day', now()) + interval '7 days 18 hours', date_trunc('day', now()) + interval '7 days 19 hours'),
    (gym1_id, beirut_id, trainer_rana_id, 'QA Spinning Cardio', 25, date_trunc('day', now()) + interval '2 days 18 hours', date_trunc('day', now()) + interval '2 days 19 hours'),
    (gym1_id, beirut_id, trainer_rana_id, 'QA CrossFit Full Scenario', 1, date_trunc('day', now()) + interval '8 days 18 hours', date_trunc('day', now()) + interval '8 days 19 hours'),
    (gym1_id, main_id, trainer_elie_id, 'QA Completed Abs Core', 16, date_trunc('day', now()) - interval '1 day' + interval '18 hours', date_trunc('day', now()) - interval '1 day' + interval '19 hours')
  ) as c(gym_id, branch_id, trainer_user_id, class_name, capacity, start_time, end_time)
  where not exists (
    select 1 from public.classes existing
    where existing.name = c.class_name and existing.branch_id = c.branch_id
  );

  select id into strength_class_id from public.classes where name = 'QA Strength Training Today';
  select id into hiit_class_id from public.classes where name = 'QA HIIT Tomorrow';
  select id into spinning_class_id from public.classes where name = 'QA Spinning Cardio';

  insert into public.class_bookings (class_id, member_id, status, booked_at)
  select strength_class_id, active_member_id, 'BOOKED', now() - interval '4 hours'
  where not exists (select 1 from public.class_bookings where class_id = strength_class_id and member_id = active_member_id);

  insert into public.class_bookings (class_id, member_id, status, booked_at)
  select spinning_class_id, vip_member_id, 'BOOKED', now() - interval '4 hours'
  where not exists (select 1 from public.class_bookings where class_id = spinning_class_id and member_id = vip_member_id);

  insert into public.class_bookings (class_id, member_id, status, booked_at)
  select hiit_class_id, history_member_id, 'CANCELLED', now() - interval '4 hours'
  where not exists (select 1 from public.class_bookings where class_id = hiit_class_id and member_id = history_member_id);

  insert into public.payments (gym_id, branch_id, member_id, membership_id, received_by_user_id, amount, method, paid_at, notes)
  select m.gym_id, m.home_branch_id, m.id, mm.id, staff_id, p.amount, p.method, now() - p.days_ago * interval '1 day', p.notes
  from (values
    ('qa.member.daypass@gymind.test', 5::numeric, 'QA Card - PAID', 1, 'QA paid one-day pass'),
    ('qa.member.active.monthly@gymind.test', 30::numeric, 'QA Card - PAID', 3, 'QA paid monthly'),
    ('qa.member.3months@gymind.test', 80::numeric, 'QA Card - PAID', 6, 'QA paid 3-month'),
    ('qa.member.vip@gymind.test', 120::numeric, 'QA Card - PAID', 2, 'QA paid VIP'),
    ('qa.member.expiring2days@gymind.test', 30::numeric, 'QA Card - PENDING', 1, 'QA pending payment'),
    ('qa.member.expired@gymind.test', 30::numeric, 'QA Card - FAILED', 20, 'QA failed payment'),
    ('qa.member.cancelled@gymind.test', 30::numeric, 'QA Card - REFUNDED', 5, 'QA refunded payment')
  ) as p(email, amount, method, days_ago, notes)
  join public.members m on m.email = p.email
  left join lateral (
    select id from public.member_memberships
    where member_id = m.id
    order by start_date desc nulls last, id desc
    limit 1
  ) mm on true
  where not exists (
    select 1 from public.payments existing
    where existing.member_id = m.id and existing.notes = p.notes
  );

  insert into public.notifications (gym_id, branch_id, title, message, created_by_user_id, created_at)
  select gym1_id, main_id, title, message, staff_id, now()
  from (values
    ('QA Membership ends in 2 days', 'Your membership ends in 2 days. Renew now to avoid interruption.'),
    ('QA Membership ends tomorrow', 'Your membership ends tomorrow. Renew now to avoid interruption.'),
    ('QA Membership expired', 'Your membership has expired. Renew to check in again.'),
    ('QA Upcoming class reminder', 'Your QA Strength Training class is coming up.'),
    ('QA Payment pending', 'You have a pending payment.'),
    ('QA Gym announcement', 'Welcome to the Gymind QA demo dataset.'),
    ('QA VIP welcome', 'Welcome to VIP All Branches access.')
  ) as n(title, message)
  where not exists (select 1 from public.notifications existing where existing.title = n.title);

  select id into notification_id from public.notifications where title = 'QA Membership ends in 2 days';
  insert into public.notification_recipients (notification_id, user_id, is_read)
  select notification_id, u.id, false
  from public.users u
  where u.email = 'qa.member.expiring2days@gymind.test'
    and not exists (select 1 from public.notification_recipients nr where nr.notification_id = notification_id and nr.user_id = u.id);

  select id into notification_id from public.notifications where title = 'QA Membership ends tomorrow';
  insert into public.notification_recipients (notification_id, user_id, is_read)
  select notification_id, u.id, false
  from public.users u
  where u.email = 'qa.member.expiringtomorrow@gymind.test'
    and not exists (select 1 from public.notification_recipients nr where nr.notification_id = notification_id and nr.user_id = u.id);

  select id into notification_id from public.notifications where title = 'QA VIP welcome';
  insert into public.notification_recipients (notification_id, user_id, is_read)
  select notification_id, u.id, false
  from public.users u
  where u.email = 'qa.member.vip@gymind.test'
    and not exists (select 1 from public.notification_recipients nr where nr.notification_id = notification_id and nr.user_id = u.id);
end $$;

commit;

-- Verification queries
select count(*) as qa_users
from public.users
where email like 'qa.%@gymind.test';

select count(*) as qa_gyms
from public.gyms
where name in ('Gymind Ablah Fitness', 'Gymind Local Gym', 'Gymind Solo Gym');

select count(*) as qa_branches
from public.branches
where name in (
  'Ablah Main Branch',
  'Ablah East Branch',
  'Beirut Branch',
  'Ablah Strength Branch',
  'Ablah Cardio Branch',
  'Ablah Solo Branch'
);

select count(*) as qa_plans
from public.membership_plans
where access_type in (
  'DAY_PASS',
  'one_branch',
  'multi-branch'
);

select count(*) as qa_members
from public.members m
join public.users u on u.id = m.user_id
where u.email like 'qa.member.%@gymind.test';

select count(*) as qa_classes
from public.classes
where name like 'QA %';

select count(*) as qa_open_sessions
from public.check_ins ci
join public.members m on m.id = ci.member_id
join public.users u on u.id = m.user_id
where u.email in ('qa.member.running@gymind.test', 'qa.member.vip.beirut@gymind.test')
  and ci.check_out_time is null;

select u.email, r.name as role, u.full_name
from public.users u
join public.roles r on r.id = u.role_id
where u.email like 'qa.%@gymind.test'
order by r.name, u.email;
